# Generated by Django 5.2.8 on 2025-11-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='poll_id',
            field=models.IntegerField(help_text='Copy-Paste the Poll this option is inherited by here!', verbose_name='Poll ID'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(help_text='Type in Option Title here!', max_length=64, verbose_name='Option Title'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, help_text='Type in the discription of the poll you want to show here!!!', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='topic',
            field=models.CharField(help_text='Type in Poll Topic here!', max_length=64, verbose_name='Poll Topic'),
        ),
    ]
